# Generated by Django 5.2.1 on 2025-08-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0002_alter_worker_position"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worker",
            name="team",
        ),
        migrations.RemoveField(
            model_name="project",
            name="teams",
        ),
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Urgent", "Urgent"),
                    ("High", "High"),
                    ("Normal", "Normal"),
                    ("Low", "Low"),
                ],
                default="Normal",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="Team",
        ),
    ]
