# Generated by Django 5.2.1 on 2025-08-26 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0003_remove_worker_team_remove_project_teams_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ("deadline",)},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ("deadline",)},
        ),
        migrations.AlterModelOptions(
            name="tasktype",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="worker",
            options={"ordering": ("username",)},
        ),
    ]
